name: Frontend CI Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.job
        uses: actions/setup-node@v2
        with:
          node-version: 20

      - name: Install Dependencies
        working-directory: frontend
        run: npm install

      - name: Run Format Check
        working-directory: frontend
        run: npm run format:check

      - name: Run Lint
        working-directory: frontend
        run: npm run lint

      - name: Run Tests
        working-directory: frontend
        run: npm run test

      - name: Run Build
        working-directory: frontend
        run: npm run build
